version: '3.8'
services:
  bot:
    container_name: discord_bot
    build: .
    depends_on:
      bot_backend_database:
        condition: service_completed_successfully
  bot_backend_database:
    container_name: discord_bot_backend_database
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=discord
    ports:
      - 5432:5432
    volumes:
      - ./data/pg_init.sql:/docker-entrypoint-initdb.d/init.sql