version: '3.8'
services:
  bot:
    container_name: discord_bot
    build: .
    depends_on:
      bot_backend_database:
        condition: service_healthy
  bot_backend_database:
    container_name: discord_bot_backend_database
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=discord
      - PGUSER=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "discord"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data/pg_init.sql:/docker-entrypoint-initdb.d/init.sql